controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login_check

registration:
    path: /api/register
    controller: App\Controller\RegistrationController::register
    methods: ['POST']



# config/routes.yaml

reset_password:
    path: /reset-password/{token}
    controller: App\Controller\ResetPasswordController::resetPassword
    methods: [GET, POST]
    

